atb:
    resource: "@ATBBundle/Resources/config/routing.yml"
    prefix:   /atb


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
