atb_homepage:
    path:     /
    defaults: { _controller: ATBBundle:Default:index }

accueil:
    path:     /accueil
    defaults: { _controller: ATBBundle:Accueil:afficherAccueil }


compte:
    path:     /compte
    defaults: { _controller: ATBBundle:Compte:index }


detail:
    path:     /detail
    defaults: { _controller: ATBBundle:Detail:index }

historique:
    path:     /historique
    defaults: { _controller: ATBBundle:Historique:index }

afficherCompte:
    path:     /afficherCompte
    defaults: { _controller: ATBBundle:Compte:afficherCompte }


afficherAccueil:
    path:     /afficherAccueil
    defaults: { _controller: ATBBundle:Accueil:afficherAccueil }

afficherDetail:
    path:     /afficherDetail/{numCompte}
    defaults: { _controller: ATBBundle:Detail:afficherDetail }

afficherDetail2:
    path:     /afficherDetail2
    defaults: { _controller: ATBBundle:Detail:afficherDetail2 }

afficherDetail3:
    path:     /afficherDetail3/{numCompte}
    defaults: { _controller: ATBBundle:Detail:afficherDetail3 }

afficherHistorique:
    path:     /afficherHistorique
    defaults: { _controller: ATBBundle:Historique:afficherHistorique }

afficherHistoriquecredit:
    path:     /afficherHistoriquecredit/{numCompte}/{typeTransaction}
    defaults: { _controller: ATBBundle:Historique:afficherHistoriquecredit }

afficherHistoriquedebit:
    path:     /afficherHistoriquedebit/{numCompte}/{typeTransaction}
    defaults: { _controller: ATBBundle:Historique:afficherHistoriquedebit }

afficherHistoriquedebit2:
    path:     /afficherHistoriquedebit2/{numCompte}
    defaults: { _controller: ATBBundle:Historique:afficherHistoriquedebit2 }
afficherHistoriquedate1:
    path:     /afficherHistoriquedate1/{numCompte}/{dateTransaction}
    defaults: { _controller: ATBBundle:Historique:afficherHistoriquedate1 }

afficherHistoriquedate2:
    path:     /afficherHistoriquedate2/{numCompte}/{typeTransaction}/{dateTransaction}
    defaults: { _controller: ATBBundle:Historique:afficherHistoriquedate2 }

afficherHistoriquedate3:
    path:     /afficherHistoriquedate3/{numCompte}/{typeTransaction}/{dateTransaction}
    defaults: { _controller: ATBBundle:Historique:afficherHistoriquedate3 }


afficherCarte:
    path:     /afficherCarte
    defaults: { _controller: ATBBundle:Carte:afficherCarte }

afficherCarte2:
    path:     /afficherCarte2/{numCompte}
    defaults: { _controller: ATBBundle:Carte:afficherCarte2 }

afficherCarte3:
    path:     /afficherCarte3/{numCompte}
    defaults: { _controller: ATBBundle:Carte:afficherCarte3 }


bloquerCarte2:
  path:     /bloquerCarte2/{numCarte}
  defaults: { _controller: ATBBundle:Carte:bloquerCarte2 }


bloquerCarte3:
    path:     /bloquerCarte3/{numCarte}
    defaults: { _controller: ATBBundle:Carte:bloquerCarte3 }

getcompte:
    path:     /getcompte
    defaults: { _controller: ATBBundle:Carte:getcompte }


search:
    path:     /search
    defaults: { _controller: ATBBundle:Autorisation:search }